// Provider registry. Order matters — earlier = higher priority for auto-fallback.

export const PROVIDERS = {
  // ── FREE CLOUD (keyless) ────────────────────────────────────────────────
  pollinations: {
    name: 'Pollinations (free, no key)',
    url: () => 'https://text.pollinations.ai/openai',
    envKey: null,
    models: ['openai', 'openai-fast', 'openai-large', 'mistral', 'llama', 'gemini'],
    defaultModel: 'openai',
    free: true,
    keyless: true,
    signupUrl: 'https://pollinations.ai',
    format: 'openai',
    supportsTools: true,
    description: 'Free cloud OpenAI-compatible proxy, no signup required.',
  },

  // ── FREE CLOUD (key required) ──────────────────────────────────────────
  groq: {
    name: 'Groq',
    url: () => 'https://api.groq.com/openai/v1/chat/completions',
    envKey: 'GROQ_API_KEY',
    models: [
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'moonshotai/kimi-k2-instruct',
      'qwen/qwen3-32b',
      'deepseek-r1-distill-llama-70b',
      'gemma2-9b-it',
    ],
    defaultModel: 'llama-3.3-70b-versatile',
    free: true,
    signupUrl: 'https://console.groq.com',
    format: 'openai',
    supportsTools: true,
    description: 'Ultra-fast inference. Llama 3.3, Kimi K2, Qwen3, DeepSeek R1 — all free tier.',
  },
  cerebras: {
    name: 'Cerebras',
    url: () => 'https://api.cerebras.ai/v1/chat/completions',
    envKey: 'CEREBRAS_API_KEY',
    models: ['llama-3.3-70b', 'llama3.1-8b', 'qwen-3-32b'],
    defaultModel: 'llama-3.3-70b',
    free: true,
    signupUrl: 'https://cloud.cerebras.ai',
    format: 'openai',
    supportsTools: true,
    description: '2000+ tokens/sec wafer-scale inference. Free tier with daily cap.',
  },
  deepseek: {
    name: 'DeepSeek',
    url: () => 'https://api.deepseek.com/chat/completions',
    envKey: 'DEEPSEEK_API_KEY',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    defaultModel: 'deepseek-chat',
    free: false,
    signupUrl: 'https://platform.deepseek.com',
    format: 'openai',
    supportsTools: true,
    description: 'DeepSeek V3 + R1 reasoner. Cheapest SOTA tool-use model around.',
  },
  openrouter: {
    name: 'OpenRouter',
    url: () => 'https://openrouter.ai/api/v1/chat/completions',
    envKey: 'OPENROUTER_API_KEY',
    models: [
      'meta-llama/llama-3.3-70b-instruct:free',
      'deepseek/deepseek-chat:free',
      'google/gemini-2.0-flash-exp:free',
      'qwen/qwen-2.5-72b-instruct:free',
      'mistralai/mistral-small-3.2-24b-instruct:free',
    ],
    defaultModel: 'meta-llama/llama-3.3-70b-instruct:free',
    free: true,
    signupUrl: 'https://openrouter.ai/keys',
    format: 'openai',
    supportsTools: true,
    description: '20+ free models behind one key. Gateway to Llama, DeepSeek, Gemini, Qwen.',
  },
  gemini: {
    name: 'Google Gemini',
    url: (_, model) => `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,
    envKey: 'GEMINI_API_KEY',
    models: ['gemini-2.0-flash', 'gemini-1.5-flash', 'gemini-1.5-pro'],
    defaultModel: 'gemini-2.0-flash',
    free: true,
    signupUrl: 'https://aistudio.google.com',
    format: 'gemini',
    supportsTools: false,
    description: 'Very capable free tier; no native tool-calling in this adapter.',
  },
  cohere: {
    name: 'Cohere',
    url: () => 'https://api.cohere.com/v1/chat',
    envKey: 'COHERE_API_KEY',
    models: ['command-r-plus', 'command-r', 'command'],
    defaultModel: 'command-r-plus',
    free: true,
    signupUrl: 'https://dashboard.cohere.com',
    format: 'cohere',
    supportsTools: false,
    description: 'Command R family; free trial tier.',
  },
  together: {
    name: 'Together AI',
    url: () => 'https://api.together.xyz/v1/chat/completions',
    envKey: 'TOGETHER_API_KEY',
    models: ['meta-llama/Llama-3-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'Qwen/Qwen2.5-72B-Instruct-Turbo'],
    defaultModel: 'meta-llama/Llama-3-70b-chat-hf',
    free: true,
    signupUrl: 'https://api.together.xyz',
    format: 'openai',
    supportsTools: true,
    description: 'Open-source model hosting with a free credit tier.',
  },
  huggingface: {
    name: 'Hugging Face',
    url: (_, model) => `https://api-inference.huggingface.co/models/${model}`,
    envKey: 'HF_API_KEY',
    models: ['mistralai/Mistral-7B-Instruct-v0.3', 'HuggingFaceH4/zephyr-7b-beta'],
    defaultModel: 'mistralai/Mistral-7B-Instruct-v0.3',
    free: true,
    signupUrl: 'https://huggingface.co/settings/tokens',
    format: 'huggingface',
    supportsTools: false,
    description: 'HF Inference API — broad model catalog, rate-limited free tier.',
  },
};

// Default priority order for auto-fallback: keyless cloud, then key-based cloud.
export const DEFAULT_ORDER = [
  'pollinations',
  'groq', 'cerebras', 'openrouter', 'gemini', 'together', 'deepseek', 'cohere', 'huggingface',
];

export function buildUrl(provider, model) {
  const base = provider.baseUrl || '';
  return typeof provider.url === 'function' ? provider.url(base, model) : provider.url;
}
