// Provider registry. Order matters — earlier = higher priority for auto-fallback.
// Providers marked `local: true` run entirely on the user's machine and take
// priority when auto-detection finds them reachable, to keep everything free
// and private by default.

export const PROVIDERS = {
  // ── LOCAL (free, private, preferred when reachable) ────────────────────
  ollama: {
    name: 'Ollama (local)',
    baseUrl: process.env.OLLAMA_URL || 'http://localhost:11434',
    // We hit the OpenAI-compatible endpoint ollama ships with since 0.1.14.
    url: (base) => `${base}/v1/chat/completions`,
    envKey: null,
    models: [],               // discovered at runtime from /api/tags
    defaultModel: process.env.OLLAMA_MODEL || 'llama3.1',
    free: true,
    local: true,
    keyless: true,
    signupUrl: 'https://ollama.com/download',
    format: 'openai',
    supportsTools: true,
    description: 'Local LLM runtime — run Llama, Qwen, Mistral, Phi on your own machine.',
  },
  lmstudio: {
    name: 'LM Studio (local)',
    baseUrl: process.env.LMSTUDIO_URL || 'http://localhost:1234',
    url: (base) => `${base}/v1/chat/completions`,
    envKey: null,
    models: [],
    defaultModel: process.env.LMSTUDIO_MODEL || 'local-model',
    free: true,
    local: true,
    keyless: true,
    signupUrl: 'https://lmstudio.ai',
    format: 'openai',
    supportsTools: true,
    description: 'Local LLM runtime with a polished desktop UI.',
  },
  llamacpp: {
    name: 'llama.cpp server (local)',
    baseUrl: process.env.LLAMACPP_URL || 'http://localhost:8080',
    url: (base) => `${base}/v1/chat/completions`,
    envKey: null,
    models: ['local'],
    defaultModel: 'local',
    free: true,
    local: true,
    keyless: true,
    signupUrl: 'https://github.com/ggerganov/llama.cpp',
    format: 'openai',
    supportsTools: true,
    description: 'Bare-metal llama.cpp `server` binary, OpenAI-compatible.',
  },

  // ── FREE CLOUD (keyless) ────────────────────────────────────────────────
  pollinations: {
    name: 'Pollinations (free, no key)',
    url: () => 'https://text.pollinations.ai/openai',
    envKey: null,
    models: ['openai', 'openai-fast', 'openai-large', 'mistral', 'llama', 'gemini'],
    defaultModel: 'openai',
    free: true,
    keyless: true,
    signupUrl: 'https://pollinations.ai',
    format: 'openai',
    supportsTools: true,
    description: 'Free cloud OpenAI-compatible proxy, no signup required.',
  },

  // ── FREE CLOUD (key required) ──────────────────────────────────────────
  groq: {
    name: 'Groq',
    url: () => 'https://api.groq.com/openai/v1/chat/completions',
    envKey: 'GROQ_API_KEY',
    models: [
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'moonshotai/kimi-k2-instruct',
      'qwen/qwen3-32b',
      'deepseek-r1-distill-llama-70b',
      'gemma2-9b-it',
    ],
    defaultModel: 'llama-3.3-70b-versatile',
    free: true,
    signupUrl: 'https://console.groq.com',
    format: 'openai',
    supportsTools: true,
    description: 'Ultra-fast inference. Llama 3.3, Kimi K2, Qwen3, DeepSeek R1 — all free tier.',
  },
  cerebras: {
    name: 'Cerebras',
    url: () => 'https://api.cerebras.ai/v1/chat/completions',
    envKey: 'CEREBRAS_API_KEY',
    models: ['llama-3.3-70b', 'llama3.1-8b', 'qwen-3-32b'],
    defaultModel: 'llama-3.3-70b',
    free: true,
    signupUrl: 'https://cloud.cerebras.ai',
    format: 'openai',
    supportsTools: true,
    description: '2000+ tokens/sec wafer-scale inference. Free tier with daily cap.',
  },
  deepseek: {
    name: 'DeepSeek',
    url: () => 'https://api.deepseek.com/chat/completions',
    envKey: 'DEEPSEEK_API_KEY',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    defaultModel: 'deepseek-chat',
    free: false,
    signupUrl: 'https://platform.deepseek.com',
    format: 'openai',
    supportsTools: true,
    description: 'DeepSeek V3 + R1 reasoner. Cheapest SOTA tool-use model around.',
  },
  openrouter: {
    name: 'OpenRouter',
    url: () => 'https://openrouter.ai/api/v1/chat/completions',
    envKey: 'OPENROUTER_API_KEY',
    models: [
      'meta-llama/llama-3.3-70b-instruct:free',
      'deepseek/deepseek-chat:free',
      'google/gemini-2.0-flash-exp:free',
      'qwen/qwen-2.5-72b-instruct:free',
      'mistralai/mistral-small-3.2-24b-instruct:free',
    ],
    defaultModel: 'meta-llama/llama-3.3-70b-instruct:free',
    free: true,
    signupUrl: 'https://openrouter.ai/keys',
    format: 'openai',
    supportsTools: true,
    description: '20+ free models behind one key. Gateway to Llama, DeepSeek, Gemini, Qwen.',
  },
  gemini: {
    name: 'Google Gemini',
    url: (_, model) => `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,
    envKey: 'GEMINI_API_KEY',
    models: [
      'gemini-2.0-flash-lite',
      'gemini-2.0-flash',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
      'gemini-1.5-pro',
    ],
    defaultModel: 'gemini-2.0-flash-lite',
    free: true,
    signupUrl: 'https://aistudio.google.com',
    format: 'gemini',
    supportsTools: false,
    description: 'Google AI Studio free tier — includes Flash-Lite (mobile-friendly). This adapter uses generateContent (no Agent tools).',
  },
  cohere: {
    name: 'Cohere',
    url: () => 'https://api.cohere.com/v1/chat',
    envKey: 'COHERE_API_KEY',
    models: ['command-r-plus', 'command-r', 'command'],
    defaultModel: 'command-r-plus',
    free: true,
    signupUrl: 'https://dashboard.cohere.com',
    format: 'cohere',
    supportsTools: false,
    description: 'Command R family; free trial tier.',
  },
  together: {
    name: 'Together AI',
    url: () => 'https://api.together.xyz/v1/chat/completions',
    envKey: 'TOGETHER_API_KEY',
    models: ['meta-llama/Llama-3-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'Qwen/Qwen2.5-72B-Instruct-Turbo'],
    defaultModel: 'meta-llama/Llama-3-70b-chat-hf',
    free: true,
    signupUrl: 'https://api.together.xyz',
    format: 'openai',
    supportsTools: true,
    description: 'Open-source model hosting with a free credit tier.',
  },
  xai: {
    name: 'xAI Grok',
    url: () => 'https://api.x.ai/v1/chat/completions',
    envKey: 'XAI_API_KEY',
    models: ['grok-3', 'grok-3-mini', 'grok-2-latest', 'grok-2-vision-latest'],
    defaultModel: 'grok-3-mini',
    free: false,
    signupUrl: 'https://console.x.ai',
    format: 'openai',
    supportsTools: true,
    description: 'xAI Grok — fast reasoning; add XAI_API_KEY (browser key in sidebar).',
  },
  anthropic: {
    name: 'Anthropic Claude',
    url: () => 'https://api.anthropic.com/v1/messages',
    envKey: 'ANTHROPIC_API_KEY',
    models: [
      'claude-sonnet-4-20250514',
      'claude-3-5-sonnet-20241022',
      'claude-3-5-haiku-20241022',
      'claude-3-opus-20240229',
    ],
    defaultModel: 'claude-3-5-sonnet-20241022',
    free: false,
    signupUrl: 'https://console.anthropic.com',
    format: 'anthropic',
    supportsTools: false,
    description: 'Claude Sonnet / Haiku / Opus — add ANTHROPIC_API_KEY or paste in sidebar. (Chat / Ask All; Agent uses OpenAI-style APIs.)',
  },
  huggingface: {
    name: 'Hugging Face',
    // Inference Providers router (OpenAI-compatible). Use your HF token (hf_…).
    url: () => 'https://router.huggingface.co/v1/chat/completions',
    envKey: 'HF_API_KEY',
    models: [
      'meta-llama/Meta-Llama-3-8B-Instruct',
      'meta-llama/Llama-3.2-3B-Instruct',
      'google/gemma-2-2b-it',
      'Qwen/Qwen2.5-7B-Instruct',
      'mistralai/Mistral-7B-Instruct-v0.3',
      'HuggingFaceH4/zephyr-7b-beta',
      'TinyLlama/TinyLlama-1.1B-Chat-v1.0',
    ],
    defaultModel: 'meta-llama/Meta-Llama-3-8B-Instruct',
    free: true,
    signupUrl: 'https://huggingface.co/settings/tokens',
    format: 'openai',
    supportsTools: false,
    description: 'HF Inference Providers (router) — same token as Hub; pick a small instruct model if one fails.',
  },
};

// Default priority order for auto-fallback. Local first, then keyless cloud,
// then key-based cloud.
export const DEFAULT_ORDER = [
  'ollama', 'lmstudio', 'llamacpp',
  'pollinations',
  'groq', 'cerebras', 'openrouter', 'gemini', 'together', 'xai', 'anthropic', 'deepseek', 'cohere', 'huggingface',
];

export function buildUrl(provider, model) {
  const base = provider.baseUrl || '';
  return typeof provider.url === 'function' ? provider.url(base, model) : provider.url;
}
